name: WorldManager
version: '2.1.0'
main: fr.mathildeuh.worldmanager.WorldManager
api-version: '1.21'
author: Mathildeuh
softdepend: [PlaceholderAPI]
commands:
  worldmanager:
    permission: "worldmanager.command"
    aliases: wm
    description: Main command of WorldManager
    usage: /<command> <subcommand> [arguments]
    permission-message: "<red>Vous n'avez pas la permission requise : <gold>worldmanager.command</gold>"
